# Generated by Django 2.2.5 on 2019-10-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PinocchioMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('item_size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatters',
            fields=[
                ('pinocchiomenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_app.PinocchioMenuItem')),
            ],
            bases=('pizza_app.pinocchiomenuitem',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('pinocchiomenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_app.PinocchioMenuItem')),
            ],
            bases=('pizza_app.pinocchiomenuitem',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('pinocchiomenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_app.PinocchioMenuItem')),
            ],
            bases=('pizza_app.pinocchiomenuitem',),
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('pinocchiomenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_app.PinocchioMenuItem')),
            ],
            bases=('pizza_app.pinocchiomenuitem',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pinocchiomenuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_app.PinocchioMenuItem')),
                ('toppings', models.ManyToManyField(to='pizza_app.Topping')),
            ],
            bases=('pizza_app.pinocchiomenuitem',),
        ),
    ]
