# Generated by Django 2.2.5 on 2019-11-07 09:10

from django.db import migrations, models
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='max_toppings',
            field=models.PositiveSmallIntegerField(default=0, validators=[rest_framework.compat.MaxValueValidator(9), rest_framework.compat.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], max_length=1, null=True),
        ),
    ]
