# Generated by Django 2.2.5 on 2019-11-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_auto_20191107_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salad',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subs',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
