# Generated by Django 2.2.5 on 2019-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_auto_20191112_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='user_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='pizza_app.CartItem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pizza_size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
