# Generated by Django 2.2.5 on 2019-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_auto_20191114_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user_cart',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], default='R', max_length=1),
        ),
    ]
